export const COMPANY_NAME = "Nutriga Akademi";
export const COMPANY_ADDRESS = "İstanbul, Türkiye";
export const COMPANY_PHONE = "+90 (212) 555 0123";
export const COMPANY_EMAIL = "info@nutrihome.com";
export const COMPANY_WORK_HOURS = "Pazartesi - Cuma: 09:00 - 18:00";
export const COMPANY_WORK_HOURS_WEEKEND = "Cumartesi: 10:00 - 16:00";
export const COMPANY_FACEBOOK_URL = "https://facebook.com/nutrihome";
export const COMPANY_TWITTER_URL = "https://twitter.com/nutrihome";
export const COMPANY_INSTAGRAM_URL = "https://instagram.com/nutrihome";
export const COMPANY_LINKEDIN_URL = "https://linkedin.com/company/nutrihome";
export const COMPANY_YOUTUBE_URL = "https://youtube.com/nutrihome";

// İletişim bilgileri
export const COMPANY_WHATSAPP_NUMBER = "905070548353"; // Gerçek WhatsApp numarası
export const COMPANY_INSTAGRAM_USERNAME = "nutrihomeakademi"; // Instagram kullanıcı adı (@ olmadan)
export const COMPANY_WHATSAPP_MESSAGE =
  "Merhaba, Nutriga Akademi ile ilgili bilgi almak istiyorum.";

export const COURSE_CATEGORIES = [
  "Tümü",
  "Temel Beslenme",
  "Klinik Beslenme",
  "Sporcu Beslenmesi",
  "Pediatrik Beslenme",
  "Geriatrik Beslenme",
  "Beslenme Danışmanlığı",
  "Fonksiyonel Beslenme",
];

export const COURSE_LEVELS = ["Başlangıç", "Orta", "İleri", "Uzman"];

export const BLOG_CATEGORIES = [
  "Tümü",
  "Beslenme Bilimi",
  "Diyet Rehberi",
  "Sağlıklı Tarifler",
  "Sporcu Beslenmesi",
  "Çocuk Beslenmesi",
  "Yaşlı Beslenmesi",
  "Hastalık ve Beslenme",
];

export const PROFESSIONS = [
  "öğrenci",
  "diyetisyen",
  "beslenme-uzmanı",
  "doktor",
  "eczacı",
  "spor-egitmeni",
  "psikolog",
  "hemşire",
  "fizyoterapist",
  "anne",
  "çocuk-gelişim-uzmanı",
  "öğretmen",
  "mühendis",
  "avukat",
  "muhasebeci",
  "pazarlama-uzmanı",
  "grafik-tasarımcı",
  "yazılımcı",
  "diğer",
];

export const UNIVERSITIES = [
  "İstanbul Üniversitesi",
  "Ankara Üniversitesi",
  "Hacettepe Üniversitesi",
  "Koç Üniversitesi",
  "Sabancı Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Orta Doğu Teknik Üniversitesi (ODTÜ)",
  "İstanbul Teknik Üniversitesi (İTÜ)",
  "Gazi Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Ege Üniversitesi",
  "Akdeniz Üniversitesi",
  "Çukurova Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Atatürk Üniversitesi",
  "Erciyes Üniversitesi",
  "Uludağ Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Pamukkale Üniversitesi",
  "Selçuk Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Marmara Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Sakarya Üniversitesi",
  "Kocaeli Üniversitesi",
  "Bilkent Üniversitesi",
  "Başkent Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "İhsan Doğramacı Bilkent Üniversitesi",
  "TED Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "Beykent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "Fatih Sultan Mehmet Üniversitesi",
  "Üsküdar Üniversitesi",
  "Maltepe Üniversitesi",
  "Doğuş Üniversitesi",
  "Özyeğin Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Yeditepe Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "Galatasaray Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Kadir Has Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "Avrupa Meslek Yüksekokulu",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "İstanbul Üniversitesi Devlet Konservatuvarı",
  "İstanbul Üniversitesi Fen Fakültesi",
  "İstanbul Üniversitesi Edebiyat Fakültesi",
  "İstanbul Üniversitesi İktisat Fakültesi",
  "İstanbul Üniversitesi İşletme Fakültesi",
  "İstanbul Üniversitesi Mühendislik Fakültesi",
  "İstanbul Üniversitesi Tıp Fakültesi",
  "İstanbul Üniversitesi Diş Hekimliği Fakültesi",
  "İstanbul Üniversitesi Eczacılık Fakültesi",
  "İstanbul Üniversitesi Veteriner Fakültesi",
  "İstanbul Üniversitesi Orman Fakültesi",
  "İstanbul Üniversitesi Su Ürünleri Fakültesi",
  "İstanbul Üniversitesi İlahiyat Fakültesi",
  "İstanbul Üniversitesi Eğitim Fakültesi",
  "İstanbul Üniversitesi Sağlık Bilimleri Fakültesi",
  "İstanbul Üniversitesi Spor Bilimleri Fakültesi",
  "İstanbul Üniversitesi İletişim Fakültesi",
  "İstanbul Üniversitesi Adalet Fakültesi",
  "İstanbul Üniversitesi Hukuk Fakültesi",
  "İstanbul Üniversitesi Siyasal Bilgiler Fakültesi",
  "İstanbul Üniversitesi Açık ve Uzaktan Eğitim Fakültesi",
  "diğer",
];

export const DEPARTMENTS = [
  "Beslenme ve Diyetetik",
  "Biyoloji",
  "Biyomühendislik",
  "Biyoteknoloji",
  "Çevre Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Endüstri Mühendisliği",
  "Fizik",
  "Gıda Mühendisliği",
  "İnşaat Mühendisliği",
  "İstatistik",
  "Kimya",
  "Kimya Mühendisliği",
  "Makine Mühendisliği",
  "Matematik",
  "Mekatronik Mühendisliği",
  "Moleküler Biyoloji ve Genetik",
  "Petrol ve Doğalgaz Mühendisliği",
  "Psikoloji",
  "Sosyoloji",
  "Tarih",
  "Türk Dili ve Edebiyatı",
  "Uluslararası İlişkiler",
  "İşletme",
  "İktisat",
  "Hukuk",
  "Tıp",
  "Diş Hekimliği",
  "Eczacılık",
  "Hemşirelik",
  "Fizyoterapi ve Rehabilitasyon",
  "Çocuk Gelişim",
  "Özel Eğitim",
  "Rehberlik ve Psikolojik Danışmanlık",
  "İngilizce Öğretmenliği",
  "Tarih Öğretmenliği",
  "Fen Bilimleri Öğretmenliği",
  "Sınıf Öğretmenliği",
  "Okul Öncesi Öğretmenliği",
  "Güzel Sanatlar",
  "Grafik Tasarım",
  "İletişim",
  "Radyo Televizyon ve Sinema",
  "Gazetecilik",
  "Halkla İlişkiler ve Reklamcılık",
  "Siyasal Bilgiler",
  "Kamu Yönetimi",
  "Maliye",
  "Bankacılık ve Finans",
  "Muhasebe",
  "Pazarlama",
  "Turizm ve Otel İşletmeciliği",
  "Lojistik",
  "Uluslararası Ticaret",
  "Bilgisayar Mühendisliği",
  "Yazılım Mühendisliği",
  "Bilgisayar Bilimleri",
  "Veri Bilimi",
  "Siber Güvenlik",
  "Elektronik ve Haberleşme Mühendisliği",
  "Uzay Mühendisliği",
  "Jeoloji Mühendisliği",
  "Harita Mühendisliği",
  "Orman Mühendisliği",
  "Tarım Mühendisliği",
  "Zootekni",
  "Su Ürünleri Mühendisliği",
  "Veterinerlik",
  "Tıp Fakültesi",
  "Diş Hekimliği Fakültesi",
  "Eczacılık Fakültesi",
  "Hemşirelik Fakültesi",
  "Sağlık Bilimleri Fakültesi",
  "Spor Bilimleri Fakültesi",
  "Eğitim Fakültesi",
  "İlahiyat Fakültesi",
  "Hukuk Fakültesi",
  "İktisat Fakültesi",
  "İşletme Fakültesi",
  "Mühendislik Fakültesi",
  "Fen Fakültesi",
  "Edebiyat Fakültesi",
  "İletişim Fakültesi",
  "Mimarlık",
  "Şehir ve Bölge Planlama",
  "Peyzaj Mimarlığı",
  "İç Mimarlık",
  "Endüstriyel Tasarım",
  "Tekstil ve Moda Tasarımı",
  "Gastronomi ve Mutfak Sanatları",
  "Aşçılık",
  "Pastacılık ve Fırıncılık",
  "diğer",
];

export const SAMPLE_COURSES = [
  {
    id: "1",
    title: "Temel Beslenme İlkeleri ve Makro Besinler",
    description:
      "Beslenmenin temel prensiplerini, makro besinlerin vücuttaki rollerini ve dengeli beslenme planlamasını kapsamlı olarak öğrenin.",
    category: "Temel Beslenme",
    level: "Başlangıç",
    price: 299,
  },
  {
    id: "2",
    title: "Klinik Beslenme ve Hastalık Yönetimi",
    description:
      "Diabetes, hipertansiyon, obezite gibi kronik hastalıklarda beslenme müdahalelerini ve tedavi protokollerini öğrenin.",
    category: "Klinik Beslenme",
    level: "İleri",
    price: 599,
  },
  {
    id: "3",
    title: "Sporcu Beslenmesi ve Performans Optimizasyonu",
    description:
      "Spor dallarına özgü beslenme stratejileri, supplementasyon ve performans artırıcı beslenme protokollerini öğrenin.",
    category: "Sporcu Beslenmesi",
    level: "Orta",
    price: 449,
  },
  {
    id: "4",
    title: "Çocuk ve Adölesan Beslenmesi",
    description:
      "0-18 yaş arası çocuklarda büyüme dönemlerine özel beslenme, mama geçişi ve beslenme sorunları yönetimini öğrenin.",
    category: "Pediatrik Beslenme",
    level: "Orta",
    price: 399,
  },
  {
    id: "5",
    title: "Yaşlı Beslenmesi ve Geriatrik Yaklaşımlar",
    description:
      "65 yaş üstü bireylerde yaşa bağlı fizyolojik değişiklikler, beslenme sorunları ve özel bakım gereksinimleri.",
    category: "Geriatrik Beslenme",
    level: "Orta",
    price: 349,
  },
];
