export const COMPANY_NAME = "Nutriga Akademi";
export const COMPANY_ADDRESS = "İstanbul, Türkiye";
export const COMPANY_PHONE = "+90 (542) 104 57 94";
export const COMPANY_EMAIL = "info@nutrigaakademi.com";
export const COMPANY_WORK_HOURS = "Pazartesi - Cumartesi: 09:00 - 18:00";
export const COMPANY_INSTAGRAM_URL =
  "https://www.instagram.com/nutrigaakademi?igsh=eW80b2tpbW1sMDVr&utm_source=qr";
// İletişim bilgileri
export const COMPANY_WHATSAPP_NUMBER = "905421045794"; // Gerçek WhatsApp numarası
export const COMPANY_INSTAGRAM_USERNAME = "nutrigaakademi"; // Instagram kullanıcı adı (@ olmadan)
export const COMPANY_WHATSAPP_MESSAGE = " ";

export const COURSE_CATEGORIES = [
  "Tümü",
  "Temel Beslenme",
  "Klinik Beslenme",
  "Sporcu Beslenmesi",
  "Pediatrik Beslenme",
  "Geriatrik Beslenme",
  "Beslenme Danışmanlığı",
  "Fonksiyonel Beslenme",
];

export const COURSE_LEVELS = ["Başlangıç", "Orta", "İleri", "Uzman"];

export const BLOG_CATEGORIES = [
  "Tümü",
  "Beslenme Bilimi",
  "Diyet Rehberi",
  "Sağlıklı Tarifler",
  "Sporcu Beslenmesi",
  "Çocuk Beslenmesi",
  "Yaşlı Beslenmesi",
  "Hastalık ve Beslenme",
];

export const PROFESSIONS = [
  "Öğrenci",
  "Tıp",
  "Fizik Tedavi ve Rehabilitasyon",
  "Beslenme ve Diyetetik",
  "Beden Eğitimi",
  "Spor Yüksekokulu",
  "Psikoloji",
  "Aşçılık",
  "Gastronomi",
  "Diğer",
];

export const UNIVERSITIES = [
  "Abdullah Gül Üniversitesi",
  "Acıbadem Mehmet Ali Aydınlar Üniversitesi",
  "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
  "Adıyaman Üniversitesi",
  "Afyon Kocatepe Üniversitesi",
  "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
  "Ağrı İbrahim Çeçen Üniversitesi",
  "Ahi Evran Üniversitesi",
  "Akdeniz Üniversitesi",
  "Aksaray Üniversitesi",
  "Alanya Alaaddin Keykubat Üniversitesi",
  "Alanya Üniversitesi",
  "Altınbaş Üniversitesi",
  "Amasya Üniversitesi",
  "Anadolu Üniversitesi",
  "Ankara Bilim Üniversitesi",
  "Ankara Hacı Bayram Veli Üniversitesi",
  "Ankara Medipol Üniversitesi",
  "Ankara Müzik ve Güzel Sanatlar Üniversitesi",
  "Ankara Sosyal Bilimler Üniversitesi",
  "Ankara Üniversitesi",
  "Antalya Belek Üniversitesi",
  "Antalya Bilim Üniversitesi",
  "Ardahan Üniversitesi",
  "Artvin Çoruh Üniversitesi",
  "Atılım Üniversitesi",
  "Atatürk Üniversitesi",
  "Avrasya Üniversitesi",
  "Ayvansaray Üniversitesi",
  "Bahçeşehir Üniversitesi",
  "Balıkesir Üniversitesi",
  "Bandırma Onyedi Eylül Üniversitesi",
  "Bartın Üniversitesi",
  "Batman Üniversitesi",
  "Bayburt Üniversitesi",
  "Bezmiâlem Vakıf Üniversitesi",
  "Bilecik Şeyh Edebali Üniversitesi",
  "Bingöl Üniversitesi",
  "Biruni Üniversitesi",
  "Bitlis Eren Üniversitesi",
  "Boğaziçi Üniversitesi",
  "Bolu Abant İzzet Baysal Üniversitesi",
  "Burdur Mehmet Akif Ersoy Üniversitesi",
  "Bursa Teknik Üniversitesi",
  "Çağ Üniversitesi",
  "Çanakkale Onsekiz Mart Üniversitesi",
  "Çankaya Üniversitesi",
  "Çankırı Karatekin Üniversitesi",
  "Çukurova Üniversitesi",
  "Demiroğlu Bilim Üniversitesi",
  "Dicle Üniversitesi",
  "Doğuş Üniversitesi",
  "Dokuz Eylül Üniversitesi",
  "Düzce Üniversitesi",
  "Ege Üniversitesi",
  "Erciyes Üniversitesi",
  "Erzincan Binali Yıldırım Üniversitesi",
  "Erzurum Teknik Üniversitesi",
  "Eskişehir Osmangazi Üniversitesi",
  "Fenerbahçe Üniversitesi",
  "Fırat Üniversitesi",
  "Galatasaray Üniversitesi",
  "Gazi Üniversitesi",
  "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
  "Gaziantep Üniversitesi",
  "Gebze Teknik Üniversitesi",
  "Giresun Üniversitesi",
  "Gümüşhane Üniversitesi",
  "Hacettepe Üniversitesi",
  "Hakkari Üniversitesi",
  "Haliç Üniversitesi",
  "Harran Üniversitesi",
  "Hasan Kalyoncu Üniversitesi",
  "Hitit Üniversitesi",
  "Iğdır Üniversitesi",
  "Işık Üniversitesi",
  "İbn Haldun Üniversitesi",
  "İhsan Doğramacı Bilkent Üniversitesi",
  "İnönü Üniversitesi",
  "İskenderun Teknik Üniversitesi",
  "İstanbul 29 Mayıs Üniversitesi",
  "İstanbul Arel Üniversitesi",
  "İstanbul Atlas Üniversitesi",
  "İstanbul Aydın Üniversitesi",
  "İstanbul Beykent Üniversitesi",
  "İstanbul Bilgi Üniversitesi",
  "İstanbul Esenyurt Üniversitesi",
  "İstanbul Gedik Üniversitesi",
  "İstanbul Gelişim Üniversitesi",
  "İstanbul Kent Üniversitesi",
  "İstanbul Kültür Üniversitesi",
  "İstanbul Medeniyet Üniversitesi",
  "İstanbul Medipol Üniversitesi",
  "İstanbul Okan Üniversitesi",
  "İstanbul Rumeli Üniversitesi",
  "İstanbul Sabahattin Zaim Üniversitesi",
  "İstanbul Sağlık ve Teknoloji Üniversitesi",
  "İstanbul Teknik Üniversitesi",
  "İstanbul Ticaret Üniversitesi",
  "İstanbul Üniversitesi",
  "İstanbul Üniversitesi-Cerrahpaşa",
  "İstinye Üniversitesi",
  "İzmir Bakırçay Üniversitesi",
  "İzmir Demokrasi Üniversitesi",
  "İzmir Ekonomi Üniversitesi",
  "İzmir Katip Çelebi Üniversitesi",
  "İzmir Kavram Üniversitesi",
  "İzmir Tınaztepe Üniversitesi",
  "İzmir Yüksek Teknoloji Enstitüsü",
  "Kadir Has Üniversitesi",
  "Kafkas Üniversitesi",
  "Kahramanmaraş İstiklal Üniversitesi",
  "Kahramanmaraş Sütçü İmam Üniversitesi",
  "Kapadokya Üniversitesi",
  "Karabük Üniversitesi",
  "Karadeniz Teknik Üniversitesi",
  "Karamanoğlu Mehmetbey Üniversitesi",
  "Kastamonu Üniversitesi",
  "Kayseri Üniversitesi",
  "Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi",
  "Kırklareli Üniversitesi",
  "Kırıkkale Üniversitesi",
  "Kilis 7 Aralık Üniversitesi",
  "Kocaeli Üniversitesi",
  "Koç Üniversitesi",
  "Konya Gıda ve Tarım Üniversitesi",
  "KTO Karatay Üniversitesi",
  "Kütahya Dumlupınar Üniversitesi",
  "Kütahya Sağlık Bilimleri Üniversitesi",
  "Malatya Turgut Özal Üniversitesi",
  "Maltepe Üniversitesi",
  "Manisa Celal Bayar Üniversitesi",
  "Mardin Artuklu Üniversitesi",
  "Marmara Üniversitesi",
  "MEF Üniversitesi",
  "Mersin Üniversitesi",
  "Mimar Sinan Güzel Sanatlar Üniversitesi",
  "Muğla Sıtkı Koçman Üniversitesi",
  "Munzur Üniversitesi",
  "Muş Alparslan Üniversitesi",
  "Namık Kemal Üniversitesi",
  "Necmettin Erbakan Üniversitesi",
  "Nevşehir Hacı Bektaş Veli Üniversitesi",
  "Niğde Ömer Halisdemir Üniversitesi",
  "Nişantaşı Üniversitesi",
  "Nuh Naci Yazgan Üniversitesi",
  "Ondokuz Mayıs Üniversitesi",
  "Ordu Üniversitesi",
  "Orta Doğu Teknik Üniversitesi",
  "Osmaniye Korkut Ata Üniversitesi",
  "Özyeğin Üniversitesi",
  "Piri Reis Üniversitesi",
  "Recep Tayyip Erdoğan Üniversitesi",
  "Sabancı Üniversitesi",
  "Sakarya Uygulamalı Bilimler Üniversitesi",
  "Sakarya Üniversitesi",
  "Sanko Üniversitesi",
  "Selçuk Üniversitesi",
  "Siirt Üniversitesi",
  "Sinop Üniversitesi",
  "Sivas Bilim ve Teknoloji Üniversitesi",
  "Sivas Cumhuriyet Üniversitesi",
  "Süleyman Demirel Üniversitesi",
  "Şırnak Üniversitesi",
  "TED Üniversitesi",
  "TOBB Ekonomi ve Teknoloji Üniversitesi",
  "Toros Üniversitesi",
  "Trakya Üniversitesi",
  "Tunceli Munzur Üniversitesi",
  "Türk Hava Kurumu Üniversitesi",
  "Türk-Alman Üniversitesi",
  "Ufuk Üniversitesi",
  "Uşak Üniversitesi",
  "Üsküdar Üniversitesi",
  "Van Yüzüncü Yıl Üniversitesi",
  "Yaşar Üniversitesi",
  "Yalova Üniversitesi",
  "Yeditepe Üniversitesi",
  "Yeni Yüzyıl Üniversitesi",
  "Yıldız Teknik Üniversitesi",
  "Yozgat Bozok Üniversitesi",
  "Zonguldak Bülent Ecevit Üniversitesi",
  "Diğer",
];

export const DEPARTMENTS = [
  "ACİL YARDIM VE AFET YÖNETİMİ(FAKÜLTE)",
  "ACİL YARDIM VE AFET YÖNETİMİ(YÜKSEKOKUL)",
  "ADLİ BİLİMLER",
  "ADLİ BİLİŞİM MÜHENDİSLİĞİ",
  "ADLİ BİLİŞİM MÜHENDİSLİĞİ(M.T.O.K.)",
  "AKTÜERYA BİLİMLERİ(FAKÜLTE)",
  "ALMAN DİLİ VE EDEBİYATI",
  "ALMANCA MÜTERCİM VE TERCÜMANLIK(FAKÜLTE)",
  "ALMANCA MÜTERCİM VE TERCÜMANLIK(YÜKSEKOKUL)",
  "ALMANCA ÖĞRETMENLİĞİ",
  "AMERİKAN KÜLTÜRÜ VE EDEBİYATI",
  "ANTRENÖRLÜK EĞİTİMİ(FAKÜLTE)",
  "ANTRENÖRLÜK EĞİTİMİ(YÜKSEKOKUL)",
  "ANTROPOLOJİ",
  "ARAP DİLİ VE EDEBİYATI",
  "ARAPÇA MÜTERCİM VE TERCÜMANLIK(FAKÜLTE)",
  "ARAPÇA MÜTERCİM VE TERCÜMANLIK(YÜKSEKOKUL)",
  "ARAPÇA ÖĞRETMENLİĞİ",
  "ARKEOLOJİ",
  "ARKEOLOJİ VE SANAT TARİHİ",
  "ARNAVUT DİLİ VE EDEBİYATI",
  "ASTRONOMİ VE UZAY BİLİMLERİ",
  "AYAKKABI TASARIMI VE ÜRETİMİ",
  "AZERBAYCAN TÜRKÇESİ VE EDEBİYATI",
  "AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ",
  "AĞAÇ İŞLERİ ENDÜSTRİ MÜHENDİSLİĞİ(M.T.O.K.)",
  "AİLE VE TÜKETİCİ BİLİMLERİ",
  "BAHÇE BİTKİLERİ",
  "BALIKÇILIK TEKNOLOJİSİ MÜHENDİSLİĞİ",
  "BANKACILIK",
  "BANKACILIK VE FİNANS",
  "BANKACILIK VE SİGORTACILIK(FAKÜLTE)",
  "BANKACILIK VE SİGORTACILIK(YÜKSEKOKUL)",
  "BASIM TEKNOLOJİLERİ",
  "BASIN VE YAYIN",
  "BATI DİLLERİ",
  "BEDEN EĞİTİMİ VE SPOR ÖĞRETMENLİĞİ(FAKÜLTE)",
  "BEDEN EĞİTİMİ VE SPOR ÖĞRETMENLİĞİ(YÜKSEKOKUL)",
  "BESLENME VE DİYETETİK(FAKÜLTE)",
  "BESLENME VE DİYETETİK(YÜKSEKOKUL)",
  "BOŞNAK DİLİ VE EDEBİYATI",
  "BULGAR DİLİ VE EDEBİYATI",
  "BULGARCA MÜTERCİM VE TERCÜMANLIK",
  "BİLGİ GÜVENLİĞİ TEKNOLOJİSİ(FAKÜLTE)",
  "BİLGİ GÜVENLİĞİ TEKNOLOJİSİ(YÜKSEKOKUL)",
  "BİLGİ VE BELGE YÖNETİMİ",
  "BİLGİSAYAR BİLİMLERİ",
  "BİLGİSAYAR MÜHENDİSLİĞİ",
  "BİLGİSAYAR MÜHENDİSLİĞİ(M.T.O.K.)",
  "BİLGİSAYAR TEKNOLOJİSİ VE BİLİŞİM SİSTEMLERİ",
  "BİLGİSAYAR VE ÖĞRETİM TEKNOLOJİLERİ ÖĞRETMENLİĞİ",
  "BİLİM TARİHİ",
  "BİLİŞİM SİSTEMLERİ MÜHENDİSLİĞİ",
  "BİLİŞİM SİSTEMLERİ MÜHENDİSLİĞİ(M.T.O.K.)",
  "BİLİŞİM SİSTEMLERİ VE TEKNOLOJİLERİ(FAKÜLTE)",
  "BİLİŞİM SİSTEMLERİ VE TEKNOLOJİLERİ(YÜKSEKOKUL)",
  "BİTKİ KORUMA",
  "BİTKİSEL ÜRETİM VE TEKNOLOJİLERİ",
  "BİYOKİMYA",
  "BİYOLOJİ",
  "BİYOLOJİ ÖĞRETMENLİĞİ",
  "BİYOMEDİKAL MÜHENDİSLİĞİ",
  "BİYOMEDİKAL MÜHENDİSLİĞİ(M.T.O.K.)",
  "BİYOMÜHENDİSLİK",
  "BİYOSİSTEM MÜHENDİSLİĞİ",
  "BİYOTEKNOLOJİ",
  "CEVHER HAZIRLAMA MÜHENDİSLİĞİ",
  "COĞRAFYA",
  "COĞRAFYA ÖĞRETMENLİĞİ",
  "COĞRAFYA(AÇIKÖĞRETİM)",
  "DENİZ ULAŞTIRMA İŞLETME MÜHENDİSLİĞİ(FAKÜLTE)",
  "DENİZ ULAŞTIRMA İŞLETME MÜHENDİSLİĞİ(YÜKSEKOKUL)",
  "DENİZCİLİK İŞLETMELERİ YÖNETİMİ",
  "DERİ MÜHENDİSLİĞİ",
  "DOĞU DİLLERİ",
  "DİJİTAL OYUN TASARIMI",
  "DİL VE KONUŞMA TERAPİSİ(FAKÜLTE)",
  "DİL VE KONUŞMA TERAPİSİ(YÜKSEKOKUL)",
  "DİLBİLİMİ",
  "DİŞ HEKİMLİĞİ",
  "EBELİK(FAKÜLTE)",
  "EBELİK(YÜKSEKOKUL)",
  "ECZACILIK",
  "EGZERSİZ VE SPOR BİLİMLERİ",
  "EGZERSİZ VE SPOR BİLİMLERİ(AÇIKÖĞRETİM)",
  "EKONOMETRİ",
  "EKONOMİ",
  "EKONOMİ VE FİNANS",
  "EL SANATLARI",
  "EL SANATLARI(M.T.O.K.)",
  "ELEKTRONİK MÜHENDİSLİĞİ",
  "ELEKTRONİK TİCARET VE YÖNETİMİ",
  "ELEKTRONİK TİCARET VE YÖNETİMİ(AÇIKÖĞRETİM)",
  "ELEKTRONİK VE HABERLEŞME MÜHENDİSLİĞİ",
  "ELEKTRİK MÜHENDİSLİĞİ",
  "ELEKTRİK-ELEKTRONİK MÜHENDİSLİĞİ",
  "ELEKTRİK-ELEKTRONİK MÜHENDİSLİĞİ(M.T.O.K.)",
  "EMLAK VE EMLAK YÖNETİMİ",
  "ENDÜSTRİ MÜHENDİSLİĞİ",
  "ENDÜSTRİYEL TASARIM MÜHENDİSLİĞİ",
  "ENDÜSTRİYEL TASARIM MÜHENDİSLİĞİ(M.T.O.K.)",
  "ENDÜSTRİYEL TASARIM(FAKÜLTE)",
  "ENDÜSTRİYEL TASARIM(YÜKSEKOKUL)",
  "ENERJİ BİLİMİ VE TEKNOLOJİLERİ",
  "ENERJİ SİSTEMLERİ MÜHENDİSLİĞİ",
  "ENERJİ SİSTEMLERİ MÜHENDİSLİĞİ(M.T.O.K.)",
  "ENERJİ YÖNETİMİ",
  "ERGOTERAPİ",
  "ERMENİ DİLİ VE KÜLTÜRÜ",
  "ESKİ YUNAN DİLİ VE EDEBİYATI",
  "FARS DİLİ VE EDEBİYATI",
  "FARSÇA MÜTERCİM VE TERCÜMANLIK",
  "FELSEFE",
  "FELSEFE GRUBU ÖĞRETMENLİĞİ",
  "FELSEFE(AÇIKÖĞRETİM)",
  "FEN BİLGİSİ ÖĞRETMENLİĞİ",
  "FOTONİK",
  "FOTOĞRAF",
  "FOTOĞRAF VE VİDEO",
  "FRANSIZ DİLİ VE EDEBİYATI",
  "FRANSIZCA MÜTERCİM VE TERCÜMANLIK",
  "FRANSIZCA ÖĞRETMENLİĞİ",
  "FİLM TASARIMI VE YAZARLIĞI",
  "FİLM TASARIMI VE YÖNETMENLİĞİ",
  "FİLM TASARIMI VE YÖNETİMİ",
  "FİNANS VE BANKACILIK(FAKÜLTE)",
  "FİNANS VE BANKACILIK(YÜKSEKOKUL)",
  "FİZYOTERAPİ VE REHABİLİTASYON(FAKÜLTE)",
  "FİZYOTERAPİ VE REHABİLİTASYON(YÜKSEKOKUL)",
  "FİZİK",
  "FİZİK MÜHENDİSLİĞİ",
  "FİZİK ÖĞRETMENLİĞİ",
  "GASTRONOMİ VE MUTFAK SANATLARI(FAKÜLTE)",
  "GASTRONOMİ VE MUTFAK SANATLARI(FAKÜLTE)(M.T.O.K)",
  "GASTRONOMİ VE MUTFAK SANATLARI(YÜKSEKOKUL)",
  "GAYRİMENKUL GELİŞTİRME VE YÖNETİMİ(FAKÜLTE)",
  "GAZETECİLİK",
  "GELENEKSEL TÜRK SANATLARI(M.T.O.K.)",
  "GEMİ MAKİNELERİ İŞLETME MÜHENDİSLİĞİ",
  "GEMİ VE DENİZ TEKNOLOJİSİ MÜHENDİSLİĞİ",
  "GEMİ VE YAT TASARIMI",
  "GEMİ İNŞAATI VE GEMİ MAKİNELERİ MÜHENDİSLİĞİ",
  "GENETİK VE BİYOMÜHENDİSLİK",
  "GENETİK VE YAŞAM BİLİMLERİ PROGRAMLARI",
  "GEOMATİK MÜHENDİSLİĞİ",
  "GERONTOLOJİ",
  "GIDA MÜHENDİSLİĞİ",
  "GIDA TEKNOLOJİSİ(FAKÜLTE)",
  "GIDA TEKNOLOJİSİ(YÜKSEKOKUL)",
  "GRAFİK",
  "GRAFİK SANATLAR(AÇIKÖĞRETİM)",
  "GRAFİK TASARIMI",
  "GRAFİK TASARIMI(M.T.O.K.)",
  "GÖRSEL SANATLAR",
  "GÖRSEL SANATLAR VE İLETİŞİM TASARIMI",
  "GÖRSEL SANATLAR(M.T.O.K.)",
  "GÖRSEL İLETİŞİM TASARIMI",
  "GÖRSEL İLETİŞİM TASARIMI(AÇIKÖĞRETİM)",
  "GÜMRÜK İŞLETME(FAKÜLTE)",
  "GÜMRÜK İŞLETME(YÜKSEKOKUL)",
  "GÜRCÜ DİLİ VE EDEBİYATI",
  "GİRİŞİMCİLİK",
  "HALKBİLİMİ",
  "HALKLA İLİŞKİLER VE REKLAMCILIK(AÇIKÖĞRETİM)",
  "HALKLA İLİŞKİLER VE REKLAMCILIK(FAKÜLTE)",
  "HALKLA İLİŞKİLER VE REKLAMCILIK(YÜKSEKOKUL)",
  "HALKLA İLİŞKİLER VE TANITIM",
  "HALKLA İLİŞKİLER VE TANITIM(AÇIKÖĞRETİM)",
  "HARİTA MÜHENDİSLİĞİ",
  "HAVACILIK ELEKTRİK VE ELEKTRONİĞİ(FAKÜLTE)",
  "HAVACILIK ELEKTRİK VE ELEKTRONİĞİ(YÜKSEKOKUL)",
  "HAVACILIK VE UZAY MÜHENDİSLİĞİ",
  "HAVACILIK YÖNETİMİ(AÇIKÖĞRETİM)",
  "HAVACILIK YÖNETİMİ(FAKÜLTE)",
  "HAVACILIK YÖNETİMİ(YÜKSEKOKUL)",
  "HAYVANSAL ÜRETİM VE TEKNOLOJİLERİ",
  "HEMŞİRELİK(FAKÜLTE)",
  "HEMŞİRELİK(YÜKSEKOKUL)",
  "HUKUK",
  "HUNGAROLOJİ",
  "HİDROJEOLOJİ MÜHENDİSLİĞİ",
  "HİNDOLOJİ",
  "HİTİTOLOJİ",
  "JAPON DİLİ VE EDEBİYATI",
  "JAPONCA MÜTERCİM VE TERCÜMANLIK",
  "JAPONCA ÖĞRETMENLİĞİ",
  "JEOFİZİK MÜHENDİSLİĞİ",
  "JEOLOJİ MÜHENDİSLİĞİ",
  "KAMU YÖNETİMİ",
  "KAMU YÖNETİMİ(AÇIKÖĞRETİM)",
  "KANATLI HAYVAN YETİŞTİRİCİLİĞİ",
  "KARŞILAŞTIRMALI EDEBİYAT",
  "KAZAK DİLİ VE EDEBİYATI",
  "KENTSEL TASARIM VE PEYZAJ MİMARLIĞI",
  "KLASİK ARKEOLOJİ",
  "KONTROL VE OTOMASYON MÜHENDİSLİĞİ",
  "KORE DİLİ VE EDEBİYATI",
  "KURGU, SES VE GÖRÜNTÜ YÖNETİMİ",
  "KUYUMCULUK VE MÜCEVHER TASARIMI(FAKÜLTE)",
  "KÜLTÜR VARLIKLARINI KORUMA VE ONARIM(FAKÜLTE)",
  "KÜLTÜR VARLIKLARINI KORUMA VE ONARIM(YÜKSEKOKUL)",
  "KÜLTÜR VE İLETİŞİM BİLİMLERİ",
  "KÜRESEL SİYASET VE ULUSLARARASI İLİŞKİLER",
  "KÜRT DİLİ VE EDEBİYATI",
  "KİMYA",
  "KİMYA MÜHENDİSLİĞİ",
  "KİMYA ÖĞRETMENLİĞİ",
  "KİMYA-BİYOLOJİ MÜHENDİSLİĞİ",
  "LATİN DİLİ VE EDEBİYATI",
  "LEH DİLİ VE EDEBİYATI",
  "LOJİSTİK YÖNETİMİ(FAKÜLTE)",
  "LOJİSTİK YÖNETİMİ(YÜKSEKOKUL)",
  "MADEN MÜHENDİSLİĞİ",
  "MAKİNE MÜHENDİSLİĞİ",
  "MAKİNE MÜHENDİSLİĞİ(M.T.O.K.)",
  "MALZEME BİLİMİ VE MÜHENDİSLİĞİ",
  "MALZEME BİLİMİ VE NANOTEKNOLOJİ MÜHENDİSLİĞİ",
  "MALZEME BİLİMİ VE TEKNOLOJİLERİ",
  "MALİYE",
  "MALİYE(AÇIKÖĞRETİM)",
  "MATEMATİK",
  "MATEMATİK MÜHENDİSLİĞİ",
  "MATEMATİK VE BİLGİSAYAR BİLİMLERİ",
  "MATEMATİK ÖĞRETMENLİĞİ",
  "MEDYA VE GÖRSEL SANATLAR",
  "MEDYA VE İLETİŞİM",
  "MEKATRONİK MÜHENDİSLİĞİ",
  "MEKATRONİK MÜHENDİSLİĞİ(M.T.O.K.)",
  "METALURJİ VE MALZEME MÜHENDİSLİĞİ",
  "METALURJİ VE MALZEME MÜHENDİSLİĞİ(M.T.O.K.)",
  "METEOROLOJİ MÜHENDİSLİĞİ",
  "MODA TASARIMI(FAKÜLTE)",
  "MODA TASARIMI(FAKÜLTE)(M.T.O.K)",
  "MODA TASARIMI(YÜKSEKOKUL)",
  "MOLEKÜLER BİYOLOJİ VE GENETİK",
  "MOLEKÜLER BİYOTEKNOLOJİ",
  "MUHASEBE VE FİNANS YÖNETİMİ(FAKÜLTE)",
  "MUHASEBE VE FİNANS YÖNETİMİ(YÜKSEKOKUL)",
  "MÜHENDİSLİK PROGRAMLARI",
  "MÜHENDİSLİK VE DOĞA BİLİMLERİ PROGRAMLARI",
  "MÜTERCİM-TERCÜMANLIK",
  "MÜZECİLİK",
  "MİMARLIK",
  "NANOBİLİM VE NANOTEKNOLOJİ",
  "NANOTEKNOLOJİ MÜHENDİSLİĞİ",
  "NÜKLEER ENERJİ MÜHENDİSLİĞİ",
  "ODYOLOJİ(FAKÜLTE)",
  "ODYOLOJİ(YÜKSEKOKUL)",
  "OKUL ÖNCESİ ÖĞRETMENLİĞİ",
  "OPTİK VE AKUSTİK MÜHENDİSLİĞİ",
  "ORGANİK TARIM İŞLETMECİLİĞİ(FAKÜLTE)",
  "ORGANİK TARIM İŞLETMECİLİĞİ(YÜKSEKOKUL)",
  "ORMAN ENDÜSTRİSİ MÜHENDİSLİĞİ",
  "ORMAN MÜHENDİSLİĞİ",
  "ORTEZ VE PROTEZ",
  "OTEL YÖNETİCİLİĞİ",
  "OTOMOTİV MÜHENDİSLİĞİ",
  "OTOMOTİV MÜHENDİSLİĞİ(M.T.O.K.)",
  "PAZARLAMA(FAKÜLTE)",
  "PAZARLAMA(YÜKSEKOKUL)",
  "PERFÜZYON",
  "PETROL VE DOĞALGAZ MÜHENDİSLİĞİ",
  "PEYZAJ MİMARLIĞI",
  "POLİMER MALZEME MÜHENDİSLİĞİ",
  "POLİTİKA VE EKONOMİ",
  "PROTOHİSTORYA VE ÖN ASYA ARKEOLOJİSİ",
  "PSİKOLOJİ",
  "PSİKOLOJİK DANIŞMANLIK VE REHBERLİK",
  "PSİKOLOJİK DANIŞMANLIK VE REHBERLİK ÖĞRETMENLİĞİ",
  "PİLOTAJ(FAKÜLTE)",
  "PİLOTAJ(YÜKSEKOKUL)",
  "RADYO, TELEVİZYON VE SİNEMA",
  "RAYLI SİSTEMLER MÜHENDİSLİĞİ",
  "REHBERLİK VE PSİKOLOJİK DANIŞMANLIK",
  "REKLAM TASARIMI VE İLETİŞİMİ",
  "REKLAMCILIK",
  "REKLAMCILIK(AÇIKÖĞRETİM)",
  "REKREASYON YÖNETİMİ(FAKÜLTE)",
  "REKREASYON YÖNETİMİ(FAKÜLTE)(M.T.O.K)",
  "REKREASYON YÖNETİMİ(YÜKSEKOKUL)",
  "REKREASYON(AÇIKÖĞRETİM)",
  "REKREASYON(FAKÜLTE)",
  "RUS DİLİ VE EDEBİYATI",
  "RUS DİLİ VE EDEBİYATI ÖĞRETMENLİĞİ",
  "RUS VE İNGİLİZ DİLLERİ VE EDEBİYATLARI",
  "RUSÇA MÜTERCİM VE TERCÜMANLIK(FAKÜLTE)",
  "RUSÇA MÜTERCİM VE TERCÜMANLIK(YÜKSEKOKUL)",
  "SANAT TARİHİ",
  "SANAT VE KÜLTÜR YÖNETİMİ",
  "SANAT VE SOSYAL BİLİMLER PROGRAMLARI",
  "SAĞLIK YÖNETİMİ(AÇIKÖĞRETİM)",
  "SAĞLIK YÖNETİMİ(FAKÜLTE)",
  "SAĞLIK YÖNETİMİ(YÜKSEKOKUL)",
  "SERMAYE PİYASASI(FAKÜLTE)",
  "SEYAHAT İŞLETMECİLİĞİ",
  "SEYAHAT İŞLETMECİLİĞİ VE TURİZM REHBERLİĞİ",
  "SINIF ÖĞRETMENLİĞİ",
  "SOSYAL BİLGİLER ÖĞRETMENLİĞİ",
  "SOSYAL HİZMET(AÇIKÖĞRETİM)",
  "SOSYAL HİZMET(FAKÜLTE)",
  "SOSYAL HİZMET(YÜKSEKOKUL)",
  "SOSYOLOJİ",
  "SOSYOLOJİ(AÇIKÖĞRETİM)",
  "SPOR YÖNETİCİLİĞİ(FAKÜLTE)",
  "SPOR YÖNETİCİLİĞİ(YÜKSEKOKUL)",
  "SU BİLİMLERİ VE MÜHENDİSLİĞİ",
  "SU ÜRÜNLERİ MÜHENDİSLİĞİ",
  "SÜMEROLOJİ",
  "SÜRYANİ DİLİ VE EDEBİYATI",
  "SÜT TEKNOLOJİSİ",
  "SİGORTACILIK VE AKTÜERYA BİLİMLERİ",
  "SİGORTACILIK VE RİSK YÖNETİMİ",
  "SİGORTACILIK VE SOSYAL GÜVENLİK",
  "SİGORTACILIK(FAKÜLTE)",
  "SİGORTACILIK(YÜKSEKOKUL)",
  "SİNEMA VE DİJİTAL MEDYA",
  "SİNEMA VE TELEVİZYON",
  "SİNOLOJİ",
  "SİYASAL BİLİMLER",
  "SİYASET BİLİMİ",
  "SİYASET BİLİMİ VE KAMU YÖNETİMİ",
  "SİYASET BİLİMİ VE KAMU YÖNETİMİ(AÇIKÖĞRETİM)",
  "SİYASET BİLİMİ VE ULUSLARARASI İLİŞKİLER",
  "SİYASET BİLİMİ VE ULUSLARARASI İLİŞKİLER(AÇIKÖĞRETİM)",
  "TAKI TASARIMI İMALATI",
  "TAKI TASARIMI(FAKÜLTE)",
  "TAKI TASARIMI(YÜKSEKOKUL)",
  "TAPU KADASTRO",
  "TARIM EKONOMİSİ",
  "TARIM MAKİNELERİ VE TEKNOLOJİLERİ MÜHENDİSLİĞİ",
  "TARIM TİCARETİ VE İŞLETMECİLİĞİ",
  "TARIMSAL BİYOTEKNOLOJİ",
  "TARIMSAL GENETİK MÜHENDİSLİĞİ",
  "TARIMSAL YAPILAR VE SULAMA",
  "TARLA BİTKİLERİ",
  "TARİH",
  "TARİH ÖNCESİ ARKEOLOJİSİ",
  "TARİH ÖĞRETMENLİĞİ",
  "TARİH(AÇIKÖĞRETİM)",
  "TEKNOLOJİ VE BİLGİ YÖNETİMİ",
  "TEKSTİL MÜHENDİSLİĞİ",
  "TEKSTİL MÜHENDİSLİĞİ(M.T.O.K.)",
  "TEKSTİL TASARIMI",
  "TEKSTİL TASARIMI(M.T.O.K.)",
  "TEKSTİL VE MODA TASARIMI(AÇIKÖĞRETİM)",
  "TEKSTİL VE MODA TASARIMI(FAKÜLTE)",
  "TEKSTİL VE MODA TASARIMI(YÜKSEKOKUL)",
  "TELEVİZYON HABERCİLİĞİ VE PROGRAMCILIĞI",
  "TIP",
  "TIP MÜHENDİSLİĞİ",
  "TOHUM BİLİMİ VE TEKNOLOJİSİ",
  "TOPRAK BİLİMİ VE BİTKİ BESLEME",
  "TURİZM REHBERLİĞİ(FAKÜLTE)",
  "TURİZM REHBERLİĞİ(YÜKSEKOKUL)",
  "TURİZM VE OTEL İŞLETMECİLİĞİ",
  "TURİZM İŞLETMECİLİĞİ(FAKÜLTE)",
  "TURİZM İŞLETMECİLİĞİ(YÜKSEKOKUL)",
  "TÜRK DİLİ VE EDEBİYATI",
  "TÜRK DİLİ VE EDEBİYATI ÖĞRETMENLİĞİ",
  "TÜRK DİLİ VE EDEBİYATI(AÇIKÖĞRETİM)",
  "TÜRK HALKBİLİMİ",
  "TÜRK İSLAM ARKEOLOJİSİ",
  "TÜRKOLOJİ",
  "TÜRKÇE ÖĞRETMENLİĞİ",
  "TÜTÜN EKSPERLİĞİ",
  "TİYATRO ELEŞTİRMENLİĞİ VE DRAMATURJİ",
  "UKRAYNA DİLİ VE EDEBİYATI",
  "ULUSLARARASI FİNANS",
  "ULUSLARARASI FİNANS VE BANKACILIK",
  "ULUSLARARASI GİRİŞİMCİLİK",
  "ULUSLARARASI TİCARET VE FİNANS",
  "ULUSLARARASI TİCARET VE FİNANSMAN(FAKÜLTE)",
  "ULUSLARARASI TİCARET VE FİNANSMAN(YÜKSEKOKUL)",
  "ULUSLARARASI TİCARET VE LOJİSTİK(AÇIKÖĞRETİM))",
  "ULUSLARARASI TİCARET VE LOJİSTİK(FAKÜLTE)",
  "ULUSLARARASI TİCARET VE LOJİSTİK(YÜKSEKOKUL)",
  "ULUSLARARASI TİCARET VE İŞLETMECİLİK(FAKÜLTE)",
  "ULUSLARARASI TİCARET VE İŞLETMECİLİK(YÜKSEKOKUL)",
  "ULUSLARARASI TİCARET(FAKÜLTE)",
  "ULUSLARARASI TİCARET(YÜKSEKOKUL)",
  "ULUSLARARASI İLİŞKİLER",
  "ULUSLARARASI İLİŞKİLER(AÇIKÖĞRETİM)",
  "ULUSLARARASI İŞLETME YÖNETİMİ",
  "URDU DİLİ VE EDEBİYATI",
  "UZAY BİLİMLERİ VE TEKNOLOJİLERİ",
  "UZAY MÜHENDİSLİĞİ",
  "UZAY VE UYDU MÜHENDİSLİĞİ",
  "UÇAK BAKIM VE ONARIM(FAKÜLTE)",
  "UÇAK BAKIM VE ONARIM(YÜKSEKOKUL)",
  "UÇAK ELEKTRİK VE ELEKTRONİĞİ",
  "UÇAK GÖVDE VE MOTOR BAKIMI(FAKÜLTE)",
  "UÇAK GÖVDE VE MOTOR BAKIMI(YÜKSEKOKUL)",
  "UÇAK MÜHENDİSLİĞİ",
  "VETERİNERLİK",
  "YABAN HAYATI EKOLOJİSİ VE YÖNETİMİ",
  "YAPAY ZEKA MÜHENDİSLİĞİ",
  "YAPAY ZEKA VE VERİ MÜHENDİSLİĞİ",
  "YAZILIM GELİŞTİRME",
  "YAZILIM MÜHENDİSLİĞİ",
  "YAZILIM MÜHENDİSLİĞİ(M.T.O.K.)",
  "YENİ MEDYA VE İLETİŞİM",
  "YENİ MEDYA(FAKÜLTE)",
  "YENİ MEDYA(YÜKSEKOKUL)",
  "YEREL YÖNETİMLER",
  "YUNAN DİLİ VE EDEBİYATI",
  "YÖNETİM BİLİMLERİ PROGRAMLARI",
  "YÖNETİM BİLİŞİM SİSTEMLERİ(AÇIKÖĞRETİM)",
  "YÖNETİM BİLİŞİM SİSTEMLERİ(FAKÜLTE)",
  "YÖNETİM BİLİŞİM SİSTEMLERİ(YÜKSEKOKUL)",
  "YİYECEK VE İÇECEK İŞLETMECİLİĞİ",
  "ZAZA DİLİ VE EDEBİYATI",
  "ZOOTEKNİ",
  "ZİRAAT MÜHENDİSLİĞİ PROGRAMLARI",
  "ÇALIŞMA EKONOMİSİ VE ENDÜSTRİ İLİŞKİLERİ",
  "ÇALIŞMA EKONOMİSİ VE ENDÜSTRİ İLİŞKİLERİ(AÇIKÖĞRETİM)",
  "ÇAĞDAŞ TÜRK LEHÇELERİ VE EDEBİYATLARI",
  "ÇAĞDAŞ YUNAN DİLİ VE EDEBİYATI",
  "ÇERKEZ DİLİ VE KÜLTÜRÜ",
  "ÇEVRE MÜHENDİSLİĞİ",
  "ÇEVİRİBİLİMİ",
  "ÇOCUK GELİŞİMİ(AÇIKÖĞRETİM)",
  "ÇOCUK GELİŞİMİ(FAKÜLTE)",
  "ÇOCUK GELİŞİMİ(YÜKSEKOKUL)",
  "ÇİN DİLİ VE EDEBİYATI",
  "ÇİNCE MÜTERCİM VE TERCÜMANLIK",
  "ÇİZGİ FİLM VE ANİMASYON",
  "ÖZEL EĞİTİM ÖĞRETMENLİĞİ",
  "İBRANİ DİLİ VE KÜLTÜRÜ",
  "İKTİSADİ VE İDARİ BİLİMLER PROGRAMLARI",
  "İKTİSADİ VE İDARİ PROGRAMLAR",
  "İKTİSAT",
  "İKTİSAT(AÇIKÖĞRETİM)",
  "İLAHİYAT",
  "İLAHİYAT(M.T.O.K.)",
  "İLETİŞİM",
  "İLETİŞİM BİLİMLERİ",
  "İLETİŞİM SANATLARI",
  "İLETİŞİM TASARIMI VE YÖNETİMİ",
  "İLETİŞİM VE TASARIMI",
  "İLKÖĞRETİM MATEMATİK ÖĞRETMENLİĞİ",
  "İMALAT MÜHENDİSLİĞİ",
  "İNGİLİZ DİLBİLİMİ",
  "İNGİLİZ DİLİ VE EDEBİYATI",
  "İNGİLİZ VE RUS DİLLERİ VE EDEBİYATLARI",
  "İNGİLİZCE MÜTERCİM VE TERCÜMANLIK(FAKÜLTE)",
  "İNGİLİZCE MÜTERCİM VE TERCÜMANLIK(YÜKSEKOKUL)",
  "İNGİLİZCE ÖĞRETMENLİĞİ",
  "İNGİLİZCE, FRANSIZCA MÜTERCİM VE TERCÜMANLIK",
  "İNSAN KAYNAKLARI YÖNETİMİ(AÇIKÖĞRETİM)",
  "İNSAN KAYNAKLARI YÖNETİMİ(FAKÜLTE)",
  "İNŞAAT MÜHENDİSLİĞİ",
  "İNŞAAT MÜHENDİSLİĞİ(M.T.O.K.)",
  "İSLAM BİLİMLERİ",
  "İSLAM İKTİSADI VE FİNANS",
  "İSLAMİ İLİMLER",
  "İSLAMİ İLİMLER(M.T.O.K.)",
  "İSPANYOL DİLİ VE EDEBİYATI",
  "İSTATİSTİK",
  "İSTATİSTİK VE BİLGİSAYAR BİLİMLERİ",
  "İTALYAN DİLİ VE EDEBİYATI",
  "İÇ MİMARLIK",
  "İÇ MİMARLIK VE ÇEVRE TASARIMI",
  "İŞ SAĞLIĞI VE GÜVENLİĞİ(AÇIKÖĞRETİM)",
  "İŞ SAĞLIĞI VE GÜVENLİĞİ(FAKÜLTE)",
  "İŞ SAĞLIĞI VE GÜVENLİĞİ(YÜKSEKOKUL)",
  "İŞLETME",
  "İŞLETME MÜHENDİSLİĞİ",
  "İŞLETME(AÇIKÖĞRETİM)",
  "ŞEHİR VE BÖLGE PLANLAMA",
];

export const SAMPLE_COURSES = [
  {
    id: "1",
    title: "Temel Beslenme İlkeleri ve Makro Besinler",
    description:
      "Beslenmenin temel prensiplerini, makro besinlerin vücuttaki rollerini ve dengeli beslenme planlamasını kapsamlı olarak öğrenin.",
    category: "Temel Beslenme",
    level: "Başlangıç",
    price: 299,
  },
  {
    id: "2",
    title: "Klinik Beslenme ve Hastalık Yönetimi",
    description:
      "Diabetes, hipertansiyon, obezite gibi kronik hastalıklarda beslenme müdahalelerini ve tedavi protokollerini öğrenin.",
    category: "Klinik Beslenme",
    level: "İleri",
    price: 599,
  },
  {
    id: "3",
    title: "Sporcu Beslenmesi ve Performans Optimizasyonu",
    description:
      "Spor dallarına özgü beslenme stratejileri, supplementasyon ve performans artırıcı beslenme protokollerini öğrenin.",
    category: "Sporcu Beslenmesi",
    level: "Orta",
    price: 449,
  },
  {
    id: "4",
    title: "Çocuk ve Adölesan Beslenmesi",
    description:
      "0-18 yaş arası çocuklarda büyüme dönemlerine özel beslenme, mama geçişi ve beslenme sorunları yönetimini öğrenin.",
    category: "Pediatrik Beslenme",
    level: "Orta",
    price: 399,
  },
  {
    id: "5",
    title: "Yaşlı Beslenmesi ve Geriatrik Yaklaşımlar",
    description:
      "65 yaş üstü bireylerde yaşa bağlı fizyolojik değişiklikler, beslenme sorunları ve özel bakım gereksinimleri.",
    category: "Geriatrik Beslenme",
    level: "Orta",
    price: 349,
  },
];
